[default]
ASTRA_DB_TOKEN="AstraCS:yneBpwTqwQfWiOpctxkhmlyK:ad7734828392ef925f732b502d37a165877cd8d7bc518480e89e04c82b2594c2"
ASTRA_DB_ENDPOINT="https://76715bec-7a1f-409d-bc03-c5fdfdc0ceb8-us-east-2.apps.astra.datastax.com"
ASTRA_DB_COLLECTION_NAME="sm_engagement_data"
LANGFLOW_CHATBOT_URL="https://api.langflow.astra.datastax.com/lf/d420e98c-2bf2-473b-a9aa-2dec2dfb2723/api/v1/run/report_assistant_sme-1?stream=false"
LANGFLOW_AUTH_TOKEN="Bearer AstraCS:NWSGeNjtIizqEEQusPQUZNgG:5063a00ebbba4a39391f3e55ad6616648f92d271a2f4a6a3ebfefaa8e4028600"
LANGFLOW_REPORT_URL="https://api.langflow.astra.datastax.com/lf/d420e98c-2bf2-473b-a9aa-2dec2dfb2723/api/v1/run/report_assistant_sme-1-1?stream=false"